# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/sidharth/Wally/cvw/fpga/constraints/constraints-ArtyA7.xdc

# IP: ip/ddr3/ddr3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3 || ORIG_REF_NAME==ddr3} -quiet] -quiet

# IP: ip/clkconverter/clkconverter.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clkconverter || ORIG_REF_NAME==clkconverter} -quiet] -quiet

# IP: ip/ahbaxibridge/ahbaxibridge.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ahbaxibridge || ORIG_REF_NAME==ahbaxibridge} -quiet] -quiet

# IP: ip/sysrst/sysrst.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sysrst || ORIG_REF_NAME==sysrst} -quiet] -quiet

# IP: ip/mmcm/mmcm.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm} -quiet] -quiet
