# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.runs/synth_1/fpgaTop.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param messaging.defaultLimit 100000
set_msg_config -id {33-285} -limit 100
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.cache/wt [current_project]
set_property parent.project_path /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/sidharth/Wally/cvw/addins/vivado-boards/new/board_files} [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.1 [current_project]
set_property ip_output_repo /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/config
  /home/sidharth/Wally/cvw/config/shared
} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/cvw.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/bpred/RASPredictor.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/adder.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/adrdec.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/adrdecs.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aes32d.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aes32e.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aes64d.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aes64e.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aes64ks1i.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aes64ks2.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aesinvmixcolumns32.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aesinvmixcolumns8.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aesinvsbox64.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aesinvsbox8.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aesinvshiftrows64.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aesmixcolumns32.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aessbox32.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aessbox8.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/aesshiftrows64.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/ahbapbbridge.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ebu/ahbcacheinterface.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ebu/ahbinterface.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/lsu/align.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/alu.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/lsu/amoalu.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/aplusbeq0.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/lsu/atomic.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/axis_adapter.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/axis_async_fifo.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/axis_async_fifo_adapter.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/axis_gmii_rx.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/axis_gmii_tx.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/binencoder.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/bmu/bitmanipalu.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/bmu/bitreverse.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/bmu/bmuctrl.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/bpred/bpred.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/bpred/btb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ebu/buscachefsm.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ebu/busfsm.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/bmu/byteop.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/cache/cache.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/cache/cacheLRU.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/cache/cachefsm.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/cache/cacheway.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/clint_apb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/bmu/clmul.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/bmu/cnt.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/comparator.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/controller.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ebu/controllerinput.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/counter.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/csa.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/csr.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/csrc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/csri.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/csrindextoaddr.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/csrm.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/csrs.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/csrsr.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/csru.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/cvtshiftcalc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/datapath.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/decoder.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/decompress.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mdu/div.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/divshiftcalc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mdu/divstep.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/lsu/dtim.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ebu/ebu.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ebu/ebufsmarb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/lsu/endianswap.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/eth_mac_1g.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/eth_mac_mii.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/eth_mac_mii_fifo.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/bmu/ext.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/extend.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fclassify.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fcmp.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fctrl.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fcvt.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrt.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtcycles.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtexpcalc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtfgen2.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtfgen4.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtfsm.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtiter.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtpostproc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtpreproc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtstage2.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtstage4.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtuotfc2.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtuotfc4.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtuslc2.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fdivsqrt/fdivsqrtuslc4cmp.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fhazard.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/flags.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fli.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/flop/flop.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/flop/flopen.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/flop/flopenl.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/flop/flopenr.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/flop/flopenrc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/flop/flopr.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fma/fma.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fma/fmaadd.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fma/fmaalign.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fma/fmaexpadd.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fma/fmalza.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fma/fmamult.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/fmashiftcalc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fma/fmasign.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fmtparams.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fpu.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fregfile.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fround.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/fsgninj.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/galoismultforward8.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/galoismultinverse8.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/gpio_apb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/bpred/gshare.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/bpred/gsharebasic.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/hazard/hazard.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/hptw.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/bpred/icpred.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/ieu.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/ifu.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/irom.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/lfsr.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/bpred/localaheadbp.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/bpred/localbpbasic.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/bpred/localrepairbp.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/lsu/lrsc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/lsu/lsu.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/lzc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/mac_ctrl_rx.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/mac_ctrl_tx.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/mac_pause_ctrl_rx.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/mac_pause_ctrl_tx.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mdu/mdu.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/mii_phy_if.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/mmu.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mdu/mul.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/mux.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/neg.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/negateintres.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/normshift.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/onehotdecoder.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/or_rows.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/kmu/packer.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/packetizer.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/packoutput.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/plic_apb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/pmachecker.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/pmpadrdec.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/pmpchecker.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/bmu/popcnt.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/postprocess.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/priorityaomux.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/priorityonehot.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/privdec.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/privileged.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/privmode.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/privpiperegs.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/mem/ram1p1rwbe.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/mem/ram1p1rwbe_64x128.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/mem/ram1p1rwbe_64x22.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/mem/ram1p1rwbe_64x44.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/mem/ram1p1rwe.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/mem/ram2p1r1wbe.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/mem/ram2p1r1wbe_1024x36.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/mem/ram2p1r1wbe_1024x68.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/mem/ram2p1r1wbe_64x32.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/ram_ahb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/aes/rconlut32.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/regchangedetect.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/regfile.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/resultsign.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/mem/rom1p1r.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/rom_ahb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/round.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/roundsign.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/rvvisynth.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/bpred/satCounter2.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/sha/sha256.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/sha/sha512_32.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/sha/sha512_64.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/shiftcorrection.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/shifter.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/postproc/specialcase.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/spi_apb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/spi_controller.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/spi_fifo.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/spill.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/ssio_sdr_in.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/cache/subcachelineread.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/lsu/subwordread.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/lsu/subwordwrite.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/lsu/swbytemask.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/generic/flop/synchronizer.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/tlb/tlb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/tlb/tlbcam.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/tlb/tlbcamline.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/tlb/tlbcontrol.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/tlb/tlblru.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/tlb/tlbmixer.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/tlb/tlbram.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/tlb/tlbramline.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/privileged/trap.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/rvvi/triggergen.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ifu/bpred/twoBitPredictor.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/uartPC16550D.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/uart_apb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/uncore/uncore.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/unpack.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/fpu/unpackinput.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/mmu/tlb/vm64check.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/wally/wallypipelinedcore.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/wally/wallypipelinedsoc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/bmu/zbb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/bmu/zbc.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/kmu/zbkb.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/kmu/zbkx.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/kmu/zipper.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/kmu/zknde32.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/kmu/zknde64.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/kmu/zknh32.sv
  /home/sidharth/Wally/cvw/fpga/src/CopiedFiles_do_not_add_to_repo/ieu/kmu/zknh64.sv
  /home/sidharth/Wally/cvw/fpga/src/fpgaTopArtyA7.sv
}
read_ip -quiet /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.srcs/sources_1/ip/ddr3/ddr3.xci
set_property used_in_implementation false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3.xdc]

read_ip -quiet /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.srcs/sources_1/ip/clkconverter/clkconverter.xci
set_property used_in_synthesis false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/clkconverter/clkconverter_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/clkconverter/clkconverter_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/clkconverter/clkconverter_ooc.xdc]

read_ip -quiet /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.srcs/sources_1/ip/ahbaxibridge/ahbaxibridge.xci
set_property used_in_implementation false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/ahbaxibridge/ahbaxibridge_ooc.xdc]

read_ip -quiet /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.srcs/sources_1/ip/sysrst/sysrst.xci
set_property used_in_implementation false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/sysrst/sysrst_board.xdc]
set_property used_in_implementation false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/sysrst/sysrst.xdc]
set_property used_in_implementation false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/sysrst/sysrst_ooc.xdc]

read_ip -quiet /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.srcs/sources_1/ip/mmcm/mmcm.xci
set_property used_in_implementation false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/mmcm/mmcm_board.xdc]
set_property used_in_implementation false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/mmcm/mmcm.xdc]
set_property used_in_implementation false [get_files -all /home/sidharth/Wally/cvw/fpga/generator/WallyFPGA.gen/sources_1/ip/mmcm/mmcm_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sidharth/Wally/cvw/fpga/constraints/constraints-ArtyA7.xdc
set_property used_in_implementation false [get_files /home/sidharth/Wally/cvw/fpga/constraints/constraints-ArtyA7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fpgaTop -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpgaTop.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file fpgaTop_utilization_synth.rpt -pb fpgaTop_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
